# Generated by Django 3.2.5 on 2021-08-23 13:46

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Onderwerp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=128)),
                ('letter', models.CharField(default='A', max_length=4)),
            ],
            options={
                'ordering': ['letter'],
            },
        ),
        migrations.CreateModel(
            name='Tijdsfactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laatste_keer', models.DateField()),
                ('intensiteit', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaardigheid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255, null=True)),
                ('nummer', models.IntegerField(blank=True, null=True)),
                ('bijbehorend_onderwerp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oefenen.onderwerp')),
                ('volgende', models.ManyToManyField(blank=True, null=True, related_name='vaardigheid_volgende', to='oefenen.Vaardigheid')),
                ('voorkennis', models.ManyToManyField(blank=True, null=True, related_name='vaardigheid_voorkennis', to='oefenen.Vaardigheid')),
            ],
            options={
                'ordering': ['bijbehorend_onderwerp', 'nummer'],
            },
        ),
        migrations.CreateModel(
            name='Voortgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voortgang', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vaardigheid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oefenen.vaardigheid')),
            ],
        ),
        migrations.CreateModel(
            name='Uitleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uitleg', ckeditor_uploader.fields.RichTextUploadingField()),
                ('voorbeeld', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('vaardigheid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='oefenen.vaardigheid')),
            ],
        ),
        migrations.CreateModel(
            name='Opgave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opgave', ckeditor_uploader.fields.RichTextUploadingField()),
                ('plaatje', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('uitwerking', ckeditor_uploader.fields.RichTextUploadingField()),
                ('vaardigheid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oefenen.vaardigheid')),
            ],
            options={
                'ordering': ['vaardigheid', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OpdrachtVoortgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoevaak_gedaan', models.IntegerField(default=0)),
                ('opdracht', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oefenen.opgave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='onderwerp',
            name='start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oefenen.vaardigheid'),
        ),
        migrations.CreateModel(
            name='Gebruiker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('intensiteit', models.IntegerField(default=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
