# Generated by Django 3.1.5 on 2021-07-03 11:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaardigheid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaardigheid', models.CharField(max_length=255)),
                ('voorkennis', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Vergelijkingen'), ('b', 'Functies'), ('c', 'Rekenkundige regels'), ('d', 'Hellingen en de afgeleide'), ('e', 'Meetkunde')], max_length=9)),
            ],
        ),
    ]
