# Generated by Django 3.1.5 on 2021-07-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0002_auto_20210703_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onderwerp',
            name='start',
        ),
        migrations.AddField(
            model_name='vaardigheid',
            name='onderwerp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oefenen.onderwerp'),
        ),
    ]
