# Generated by Django 3.1.5 on 2021-07-03 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0005_voorkennis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voorkennis',
        ),
        migrations.AlterField(
            model_name='vaardigheid',
            name='voorkennis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oefenen.vaardigheid'),
        ),
    ]
