# Generated by Django 3.1.5 on 2021-07-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0006_auto_20210703_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaardigheid',
            old_name='voorkennis',
            new_name='kennis',
        ),
    ]
