# Generated by Django 3.1.5 on 2021-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0007_auto_20210703_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voorkennis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(default='<QuerySet [<Vaardigheid: Lineaire vergelijkingen oplossen>, <Vaardigheid: Merkwaardige producten>]>', max_length=128)),
            ],
        ),
    ]
