# Generated by Django 3.1.5 on 2021-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0008_voorkennis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaardigheid',
            name='kennis',
        ),
        migrations.RemoveField(
            model_name='voorkennis',
            name='naam',
        ),
        migrations.AddField(
            model_name='voorkennis',
            name='naam',
            field=models.ManyToManyField(blank=True, null=True, to='oefenen.Vaardigheid'),
        ),
    ]
