# Generated by Django 3.1.5 on 2021-07-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0009_auto_20210703_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaardigheid',
            name='voorkennis',
            field=models.ManyToManyField(blank=True, null=True, related_name='_vaardigheid_voorkennis_+', to='oefenen.Vaardigheid'),
        ),
        migrations.DeleteModel(
            name='Voorkennis',
        ),
    ]
