# Generated by Django 3.1.5 on 2021-07-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0010_auto_20210703_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaardigheid',
            name='volgende',
            field=models.ManyToManyField(blank=True, null=True, related_name='_vaardigheid_volgende_+', to='oefenen.Vaardigheid'),
        ),
        migrations.AlterField(
            model_name='vaardigheid',
            name='bijbehorend_onderwerp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oefenen.onderwerp'),
        ),
    ]
