# Generated by Django 3.1.5 on 2021-07-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0011_auto_20210703_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaardigheid',
            options={'ordering': ['bijbehorend_onderwerp', 'pk']},
        ),
        migrations.AddField(
            model_name='vaardigheid',
            name='nummer',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vaardigheid',
            name='bijbehorend_onderwerp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oefenen.onderwerp'),
        ),
        migrations.AlterField(
            model_name='vaardigheid',
            name='naam',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
