# Generated by Django 3.1.5 on 2021-07-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0013_auto_20210703_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaardigheid',
            name='volgende',
            field=models.ManyToManyField(blank=True, related_name='_vaardigheid_volgende_+', to='oefenen.Vaardigheid'),
        ),
        migrations.AlterField(
            model_name='vaardigheid',
            name='voorkennis',
            field=models.ManyToManyField(blank=True, related_name='_vaardigheid_voorkennis_+', to='oefenen.Vaardigheid'),
        ),
        migrations.CreateModel(
            name='Voorkennis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kennis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kennis', to='oefenen.vaardigheid')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='oefenen.vaardigheid')),
            ],
        ),
    ]
