# Generated by Django 3.1.5 on 2021-07-03 14:40

from django.db import migrations
import multiselectfield.db.fields
import oefenen.models


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0014_auto_20210703_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voorkennis',
            name='kennis',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200, verbose_name=oefenen.models.Vaardigheid),
        ),
    ]
