# Generated by Django 3.1.5 on 2021-07-03 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0016_auto_20210703_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaardigheid',
            name='kennis',
        ),
        migrations.RemoveField(
            model_name='vaardigheid',
            name='voorkennis',
        ),
        migrations.CreateModel(
            name='Voorkennis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kennis', models.ManyToManyField(to='oefenen.Vaardigheid')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='oefenen.vaardigheid')),
            ],
        ),
    ]
