# Generated by Django 3.1.5 on 2021-07-03 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0019_auto_20210703_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onderwerp',
            name='start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oefenen.vaardigheid'),
        ),
        migrations.AlterField(
            model_name='vaardigheid',
            name='bijbehorend_onderwerp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oefenen.onderwerp'),
        ),
        migrations.AlterField(
            model_name='vaardigheid',
            name='nummer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Opgave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opgave', models.TextField()),
                ('antwoord', models.CharField(max_length=255)),
                ('uitwerking', models.TextField()),
                ('vaardigheid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oefenen.vaardigheid')),
            ],
        ),
    ]
