# Generated by Django 3.1.5 on 2021-07-05 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oefenen', '0021_gebruiker_voortgang'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebruiker',
            name='intensiteit',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='gebruiker',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gebruiker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='voortgang',
            name='voortgang',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='OpdrachtVoortgang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoevaak_gedaan', models.IntegerField(default=0)),
                ('opdracht', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oefenen.opgave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
