# Generated by Django 3.1.5 on 2021-07-05 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oefenen', '0022_auto_20210705_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opgave',
            options={'ordering': ['vaardigheid', 'pk']},
        ),
        migrations.AlterField(
            model_name='gebruiker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
