# Generated by Django 3.1.5 on 2021-07-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0023_auto_20210705_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='opgave',
            name='plaatje',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
