# Generated by Django 3.1.5 on 2021-07-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0024_opgave_plaatje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opgave',
            name='plaatje',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
