<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-05 20:05
=======
# Generated by Django 3.2.5 on 2021-07-05 20:00
>>>>>>> VINCENT

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0026_auto_20210705_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opgave',
            name='uitwerking',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
