# Generated by Django 3.2.5 on 2021-07-06 08:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0027_alter_opgave_uitwerking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uitleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uitleg', ckeditor.fields.RichTextField()),
                ('voorbeeld', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('vaardigheid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oefenen.vaardigheid', unique=True)),
            ],
        ),
    ]
