# Generated by Django 3.2.5 on 2021-07-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0028_uitleg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitleg',
            name='vaardigheid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='oefenen.vaardigheid'),
        ),
    ]
