# Generated by Django 3.2.5 on 2021-07-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0029_alter_uitleg_vaardigheid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opgave',
            name='antwoord',
        ),
    ]
