# Generated by Django 3.2.5 on 2021-07-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0030_remove_opgave_antwoord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tijdsfactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laatste_keer', models.DateField()),
            ],
        ),
    ]
