# Generated by Django 3.2.5 on 2021-07-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oefenen', '0031_tijdsfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tijdsfactor',
            name='intensiteit',
            field=models.IntegerField(default=100),
        ),
    ]
